import type { AchievementCategory } from './api'

export const CATEGORY_ORDER: AchievementCategory[] = [
  'onboarding', 'organization', 'payments', 'goals', 'volume', 'financial',
]

export const CATEGORY_LABELS: Record<AchievementCategory, string> = {
  onboarding:   'Primeiros Passos',
  organization: 'Organização Financeira',
  payments:     'Pagamentos & Disciplina',
  goals:        'Metas & Economia',
  volume:       'Volume & Engajamento',
  financial:    'Financeiro Avançado',
}

export const CATEGORY_COLORS: Record<AchievementCategory, string> = {
  onboarding:   '#3b82f6',
  organization: '#818cf8',
  payments:     '#34d399',
  goals:        '#fbbf24',
  volume:       '#22d3ee',
  financial:    '#a78bfa',
}

interface AchievementMeta { name: string; desc: string; tip: string }

export const ACHIEVEMENT_TEXT: Record<string, AchievementMeta> = {
  'welcome':            { name: 'Bem-vindo ao Rook',       desc: 'Criou sua conta',                         tip: 'Crie sua conta no Rook Money' },
  'first-account':      { name: 'Primeira Conta',          desc: 'Cadastrou a primeira conta bancária',     tip: 'Registre sua primeira transação' },
  'first-income':       { name: 'Salário na Mesa',         desc: 'Cadastrou a primeira renda',              tip: 'Cadastre sua primeira fonte de renda' },
  'first-bill':         { name: 'Primeira Fatura',         desc: 'Cadastrou a primeira conta a pagar',      tip: 'Cadastre sua primeira conta a pagar' },
  'first-goal':         { name: 'Sonhador',                desc: 'Criou o primeiro objetivo',               tip: 'Crie seu primeiro objetivo financeiro' },
  'first-transaction':  { name: 'Primeira Transação',      desc: 'Registrou a primeira transação',          tip: 'Registre qualquer transação' },
  'complete-profile':   { name: 'Perfil Completo',         desc: 'Preencheu nome, email e foto',            tip: 'Adicione sua foto de perfil em Configurações' },
  'organized':          { name: 'Organizadinho',           desc: 'Contas em 3+ categorias',                 tip: 'Tenha contas em pelo menos 3 categorias' },
  'archivist':          { name: 'Arquivista',              desc: 'Contas em 7+ categorias',                 tip: 'Tenha contas em pelo menos 7 categorias' },
  'autopilot':          { name: 'No Automático',           desc: 'Criou a primeira conta recorrente',       tip: 'Crie uma conta recorrente mensal' },
  'full-autopilot':     { name: 'Piloto Automático',       desc: '10+ contas recorrentes ativas',           tip: 'Tenha 10+ contas recorrentes ativas' },
  'split-right':        { name: 'Dividindo Certo',         desc: 'Associou uma pessoa a uma conta',         tip: 'Registre uma dívida com alguém em Pessoas' },
  'financial-network':  { name: 'Rede Financeira',         desc: '5+ pessoas com contas associadas',        tip: 'Tenha 5+ pessoas com dívidas registradas' },
  'multi-income':       { name: 'Multi-Renda',             desc: '3+ fontes de renda',                      tip: 'Cadastre 3+ fontes de renda diferentes' },
  'diversified':        { name: 'Diversificado',           desc: '5+ fontes de renda',                      tip: 'Cadastre 5+ fontes de renda diferentes' },
  'full-panorama':      { name: 'Panorama Completo',       desc: 'Contas, rendas, metas e transações',      tip: 'Tenha ao menos uma de cada cadastrada' },
  'punctual':           { name: 'Pontual',                 desc: 'Pagou 5 contas no prazo',                 tip: 'Pague 5 contas antes do vencimento' },
  'super-punctual':     { name: 'Super Pontual',           desc: 'Pagou 25 contas no prazo',                tip: 'Pague 25 contas antes do vencimento' },
  'relentless':         { name: 'Implacável',              desc: 'Pagou 100 contas no prazo',               tip: 'Pague 100 contas antes do vencimento' },
  'punctuality-legend': { name: 'Lenda da Pontualidade',   desc: 'Pagou 500 contas no prazo',               tip: 'Pague 500 contas no prazo!' },
  'clean-month':        { name: 'Mês Limpo',               desc: 'Pagou todas as contas do mês',            tip: 'Pague todas as contas do mês atual' },
  'perfect-quarter':    { name: 'Trimestre Perfeito',      desc: '3 meses sem atraso',                      tip: '3 meses consecutivos sem atraso' },
  'golden-semester':    { name: 'Semestre de Ouro',        desc: '6 meses sem atraso',                      tip: '6 meses consecutivos sem atraso' },
  'flawless-year':      { name: 'Ano Impecável',           desc: '12 meses sem atraso',                     tip: '12 meses consecutivos sem atraso' },
  'cleared-month':      { name: 'Zerou o Mês',             desc: 'Nenhuma conta atrasada no mês',           tip: 'Termine o mês sem contas atrasadas' },
  'lightning-payer':    { name: 'Pagador Relâmpago',       desc: 'Pagou no mesmo dia que cadastrou',        tip: 'Cadastre e pague uma conta no mesmo dia' },
  'ahead-of-time':      { name: 'Adiantado',               desc: 'Pagou 7+ dias antes do vencimento',       tip: 'Pague uma conta com 7+ dias de antecedência' },
  'fortune-teller':     { name: 'Previsor',                desc: 'Pagou 30+ dias antes do vencimento',      tip: 'Pague uma conta com 30+ dias de antecedência' },
  'first-deposit':      { name: 'Primeiro Depósito',       desc: 'Primeira contribuição a uma meta',        tip: 'Faça seu primeiro aporte em uma meta' },
  'steady':             { name: 'Constante',               desc: '5 contribuições a metas',                 tip: 'Faça 5 aportes em metas' },
  'dedicated':          { name: 'Dedicado',                desc: '20 contribuições a metas',                tip: 'Faça 20 aportes em metas' },
  'obsessive':          { name: 'Obsessivo',               desc: '50 contribuições a metas',                tip: 'Faça 50 aportes em metas' },
  'halfway':            { name: 'Meio Caminho',            desc: '50% de qualquer meta',                    tip: 'Atinja 50% de qualquer meta' },
  'goal-reached':       { name: 'Meta Batida!',            desc: 'Completou uma meta',                      tip: 'Atinja 100% de uma meta' },
  'dream-collector':    { name: 'Colecionador de Sonhos',  desc: 'Completou 3 metas',                       tip: 'Complete 3 metas diferentes' },
  'achiever':           { name: 'Realizador',              desc: 'Completou 5 metas',                       tip: 'Complete 5 metas diferentes' },
  'dream-machine':      { name: 'Máquina de Sonhos',       desc: 'Completou 10 metas',                      tip: 'Complete 10 metas diferentes' },
  'heavy-deposit':      { name: 'Aporte Pesado',           desc: 'Aporte de R$1.000+',                      tip: 'Faça um aporte de R$1.000+ em uma meta' },
  'monster-deposit':    { name: 'Aporte Monstro',          desc: 'Aporte de R$5.000+',                      tip: 'Faça um aporte de R$5.000+ em uma meta' },
  'goal-millionaire':   { name: 'Milionário em Metas',     desc: 'R$10.000+ acumulados',                    tip: 'Acumule R$10.000+ somando todas as metas' },
  '10-bills':           { name: '10 Contas',               desc: 'Cadastrou 10 contas',                     tip: 'Cadastre 10 contas a pagar' },
  '50-bills':           { name: '50 Contas',               desc: 'Cadastrou 50 contas',                     tip: 'Cadastre 50 contas a pagar' },
  '100-bills':          { name: 'Centenário',              desc: 'Cadastrou 100 contas',                    tip: 'Cadastre 100 contas a pagar' },
  '500-bills':          { name: 'Maratonista',             desc: 'Cadastrou 500 contas',                    tip: 'Cadastre 500 contas a pagar' },
  '50-transactions':    { name: 'Registrador',             desc: '50 transações registradas',               tip: 'Registre 50 transações' },
  '200-transactions':   { name: 'Contador',                desc: '200 transações registradas',              tip: 'Registre 200 transações' },
  '500-transactions':   { name: 'Auditor',                 desc: '500 transações registradas',              tip: 'Registre 500 transações' },
  'veteran':            { name: 'Veterano',                desc: 'Conta ativa por 3 meses',                 tip: 'Mantenha sua conta ativa por 3 meses' },
  'rooted':             { name: 'Raiz',                    desc: 'Conta ativa por 6 meses',                 tip: 'Mantenha sua conta ativa por 6 meses' },
  'legendary':          { name: 'Lendário',                desc: 'Conta ativa por 1 ano',                   tip: 'Mantenha sua conta ativa por 1 ano' },
  'eternal':            { name: 'Eterno',                  desc: 'Conta ativa por 2 anos',                  tip: 'Mantenha sua conta ativa por 2 anos' },
  'positive-balance':   { name: 'Saldo Positivo',          desc: 'Mês com renda > despesas',                tip: 'Termine o mês com renda > despesas' },
  'surplus-3':          { name: 'Superávit x3',            desc: '3 meses com renda > despesas',            tip: '3 meses consecutivos de superávit' },
  'surplus-6':          { name: 'Superávit x6',            desc: '6 meses com renda > despesas',            tip: '6 meses consecutivos de superávit' },
  'balance-guardian':   { name: 'Guardião do Saldo',       desc: '12 meses com renda > despesas',           tip: '12 meses consecutivos de superávit' },
  'economist':          { name: 'Economista',              desc: 'Gastou menos de 80% da renda',            tip: 'Gaste menos de 80% da renda em um mês' },
  'frugal':             { name: 'Frugal',                  desc: 'Gastou menos de 50% da renda',            tip: 'Gaste menos de 50% da renda em um mês' },
  'debt-free':          { name: 'Sem Dívidas',             desc: 'Zero contas em aberto',                   tip: 'Pague todas as contas pendentes' },
  'big-payment':        { name: 'Grande Pagamento',        desc: 'Pagou uma conta de R$1.000+',             tip: 'Pague uma conta de R$1.000+' },
  'epic-payment':       { name: 'Pagamento Épico',         desc: 'Pagou uma conta de R$5.000+',             tip: 'Pague uma conta de R$5.000+' },
  'investor':           { name: 'Investidor',              desc: '3+ metas ativas simultaneamente',         tip: 'Tenha 3+ metas ativas ao mesmo tempo' },
}
